---
version: "2.1"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${APP_ROOT}/radarr:/config
      - ${MEDIA_ROOT}/movies:/movies
      - ${DOWNLOADS_ROOT}/downloads:/data
    ports:
      - 7878:7878
    networks:
      - internal
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${APP_ROOT}/sonarr:/config
      - ${MEDIA_ROOT}/tv:/tv
      - ${MEDIA_ROOT}/anime:/anime
      - ${DOWNLOADS_ROOT}/downloads:/data
    ports:
      - 8989:8989
    networks:
      - internal
    restart: unless-stopped

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    volumes:
      - ${APP_ROOT}/jackett:/config
    ports:
      - 9117:9117
    networks:
      - internal
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${APP_ROOT}/lidarr:/config
      - ${MEDIA_ROOT}/music:/music
      - ${DOWNLOADS_ROOT}/downloads:/downloads
    ports:
      - 8686:8686
    restart: unless-stopped

  readarr:
    image: lscr.io/linuxserver/readarr:nightly
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ${APP_ROOT}/readarr:/config
      - ${MEDIA_ROOT}/books:/books
      - ${DOWNLOADS_ROOT}/downloads:/downloads
    ports:
      - 8787:8787
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${APP_ROOT}/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${APP_ROOT}/overseerr:/config
    ports:
      - 5055:5055
    restart: unless-stopped

  transmission-openvpn:
    image: haugene/transmission-openvpn
    container_name: transmission
    cap_add:
      - NET_ADMIN
    volumes:
      - ${APP_ROOT}/transmission:/config
      - ${DOWNLOADS_ROOT}/downloads:/data
    environment:
      - OPENVPN_PROVIDER=NORDVPN
      - OPENVPN_CONFIG=ca1555.nordvpn.com
      - OPENVPN_USERNAME=bJrDWYfryEfaGioF1uvUAt2P
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - LOCAL_NETWORK=192.168.0.0/16
    logging:
      driver: json-file
      options:
        max-size: 10m
    networks:
      - internal
    ports:
      - "9091:9091"
    restart: unless-stopped

networks:
  internal:
