---
version: "2.1"
services:
  nginx:
    container_name: nginx
    image: nginx
    command: /bin/bash -c "envsubst < /etc/nginx/templates/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    volumes:
      - ${APP_ROOT}/templates/:/etc/nginx/templates/
    ports:
      - "80:80"
      - "443:433"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    networks:
      - internal
    extra_hosts:
      - "host.docker.internal:host-gateway"

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM} #optional
    volumes:
      - ${APP_ROOT}/plex/config:/config
      - ${MEDIA_ROOT}/tv:/tv
      - ${MEDIA_ROOT}/anime:/anime
      - ${MEDIA_ROOT}/movies:/movies
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${APP_ROOT}/radarr:/config
      - ${MEDIA_ROOT}/movies:/movies
      - ${DOWNLOADS_ROOT}/downloads:/data
    ports:
      - 7878:7878
    networks:
      - internal
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${APP_ROOT}/sonarr:/config
      - ${MEDIA_ROOT}/tv:/tv
      - ${MEDIA_ROOT}/anime:/anime
      - ${DOWNLOADS_ROOT}/downloads:/data
    ports:
      - 8989:8989
    networks:
      - internal
    restart: unless-stopped

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    volumes:
      - ${APP_ROOT}/jackett:/config
    ports:
      - 9117:9117
    networks:
      - internal
    restart: unless-stopped

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${APP_ROOT}/overseerr:/config
    ports:
      - 5055:5055
    restart: unless-stopped

  transmission-openvpn:
    image: haugene/transmission-openvpn
    container_name: transmission
    cap_add:
      - NET_ADMIN
    volumes:
      - ${APP_ROOT}/transmission:/config
      - ${DOWNLOADS_ROOT}/downloads:/data
    environment:
      - OPENVPN_PROVIDER=NORDVPN
      - OPENVPN_CONFIG=ca1555.nordvpn.com
      - OPENVPN_USERNAME=bJrDWYfryEfaGioF1uvUAt2P
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - LOCAL_NETWORK=192.168.0.0/16
    logging:
      driver: json-file
      options:
        max-size: 10m
    networks:
      - internal
    ports:
      - "9091:9091"
    restart: unless-stopped

networks:
  internal:
