
---
version: "2.1"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - ${MEDIA_ROOT}/plex/config:/config
      - ${MEDIA_ROOT}/tv:/tv
      - ${MEDIA_ROOT}/movies:/movies
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${MEDIA_ROOT}/radarr:/config
      - ${MEDIA_ROOT}/movies:/movies
      - ${MEDIA_ROOT}/downloads:/data
    ports:
      - 7878:7878
    restart: unless-stopped

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    volumes:
      - /path/to/data:/config
      - /path/to/blackhole:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

  transmission-openvpn:
    container_name: transmission
    cap_add:
        - NET_ADMIN
    volumes:
      - ${MEDIA_ROOT}/transmission:/config
      - ${MEDIA_ROOT}/downloads:/data
    environment:
        - OPENVPN_PROVIDER=NORDVPN
        - OPENVPN_CONFIG=ca1555.nordvpn.com
        - OPENVPN_USERNAME=bJrDWYfryEfaGioF1uvUAt2P
        - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
        - LOCAL_NETWORK=192.168.0.0/16
    logging:
        driver: json-file
        options:
            max-size: 10m
    ports:
        - '9091:9091'
    image: haugene/transmission-openvpn