name: 'Production Web Deploy'

on:
  push:
    branches:
      - main

jobs:
  mrsk-deploy:
    runs-on: ubuntu-22.04
    
    environment: production

    steps:
    - uses: actions/checkout@v3

    - name: Setup cloudflared CLI
      env:
        CLOUDFLARE_ACCESS_CLIENT_ID: ${{secrets.CLOUDFLARE_ACCESS_CLIENT_ID}}
        CLOUDFLARE_ACCESS_CLIENT_SECRET: ${{secrets.CLOUDFLARE_ACCESS_CLIENT_SECRET}}
      run: |
        # Add cloudflare gpg key
        sudo mkdir -p --mode=0755 /usr/share/keyrings
        curl -fsSL https://pkg.cloudflare.com/cloudflare-main.gpg | sudo tee /usr/share/keyrings/cloudflare-main.gpg >/dev/null
        
        # Add this repo to your apt repositories
        echo 'deb [signed-by=/usr/share/keyrings/cloudflare-main.gpg] https://pkg.cloudflare.com/cloudflared focal main' | sudo tee /etc/apt/sources.list.d/cloudflared.list
        
        # install cloudflared
        sudo apt-get update && sudo apt-get install cloudflared

    - name: Setup SSH Proxy
      run: |
        mkdir ~/.ssh
        touch ~/.ssh/config
        echo "
        Host dev.pmfit.org
        ProxyCommand cloudflared access ssh --hostname %h
        " | tee -a ~/.ssh/config

    - name: Setup SSH Keys
      uses: webfactory/ssh-agent@v0.7.0
      with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Install MRSK & Ruby Deps
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0' # Not needed with a .ruby-version file
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically

    - name: MRSK Deploy
      env:
        MRSK_REGISTRY_PASSWORD: ${{ secrets.MRSK_REGISTRY_PASSWORD }}
      run: bundle exec mrsk deploy