name: 'Production Web Deploy'

on:
  push:
    branches:
      - main

jobs:
  mrsk-deploy:
    runs-on: ubuntu-22.04
    
    environment: production

    steps:
    - uses: actions/checkout@v3
    - name: Setup warp
      env:
        CLOUDFLARE_ACCESS_CLIENT_ID: ${{secrets.CLOUDFLARE_ACCESS_CLIENT_ID}}
        CLOUDFLARE_ACCESS_CLIENT_SECRET: ${{secrets.CLOUDFLARE_ACCESS_CLIENT_SECRET}}
      run: |
        sudo mkdir /var/lib/cloudflare-warp
        sudo touch /var/lib/cloudflare-warp/mdm.xml

        sudo echo "
        <dict>
          <key>organization</key>
          <string>pmfit</string>
          <key>auth_client_id</key>
          <string>$CLOUDFLARE_ACCESS_CLIENT_ID</string>
          <key>auth_client_secret</key>
          <string>$CLOUDFLARE_ACCESS_CLIENT_SECRET</string>
        </dict>" | sudo tee -a /var/lib/cloudflare-warp/mdm.xml
        
        echo "CONTENT:"
        sudo cat /var/lib/cloudflare-warp/mdm.xml | echo $1

        sudo apt update
        sudo apt install libnss3-tools desktop-file-utils
        wget https://pkg.cloudflareclient.com/uploads/cloudflare_warp_2023_3_398_1_amd64_ddd2a223f7.deb
        sudo dpkg -i cloudflare_warp_2023_3_398_1_amd64_ddd2a223f7.deb

        warp-cli --accept-tos register
        warp-cli --accept-tos connect
        curl https://www.cloudflare.com/cdn-cgi/trace/

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0' # Not needed with a .ruby-version file
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically

    - uses: webfactory/ssh-agent@v0.7.0
      with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: MRSK Deploy
      run: bundle exec mrsk deploy